id: thermal_camera
name: Thermal Camera
name[zh]: 热成像仪
version: 1.0.0
icon: assets/thermal.json
author: Sipeed Ltd
desc: Thermal Camera
desc[zh]: 热成像仪
files:
  app.yaml: app.yaml
  assets: assets
  README.md: README.md

