id: dart                         # 唯一 ID，使用小写字母并用下划线分隔单词
name: dart
name[zh]: 飞镖                  # 中文名称
version: 1.9.3                     # 版本号，格式为 major.minor.patch
icon:            # 图标文件，可以是 png 或 lottie json 文件，或为空
author: kid-king-x
desc: dart begin
desc[zh]: 飞镖启动涵道

#### 包含文件方法 1：
# 默认情况下，会包含项目目录中的所有文件，除了排除文件
exclude:       # 不支持正则表达式，.git 和 __pycache__ 总是会被排除
  - .vscode
  - compile
  - build
  - dist
# extra_include:
#   src: dst
#   build/filename123: filename123

#### 包含文件方法 2：
# 白名单模式，只包含 files 字典中的文件。
# 如果没有此键或值为空，将使用方法 1。
# files:
#   - assets
#   - hello.py
#   - main.py

#### 包含文件方法 2.1：
# 白名单模式，只包含 files 字典中的文件。
# 如果没有此键或值为空，将使用方法 1。
# files:
#   assets: assets

